#ifndef CAMERADETECTOR_GLOBAL_H
#define CAMERADETECTOR_GLOBAL_H

#if defined(CAMERADETECTOR_LIBRARY)
#  define CAMERADETECTOR_EXPORT Q_DECL_EXPORT
#else
#  define CAMERADETECTOR_EXPORT Q_DECL_IMPORT
#endif

#endif // CAMERADETECTOR_GLOBAL_H
