#ifndef RECIPEENGINE_GLOBAL_H
#define RECIPEENGINE_GLOBAL_H

#if defined(RECIPEENGINE_LIBRARY)
#  define RECIPEENGINE_EXPORT Q_DECL_EXPORT
#else
#  define RECIPEENGINE_EXPORT Q_DECL_IMPORT
#endif

#endif // RECIPEENGINE_GLOBAL_H
