#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(MLCOLORIMETERIMAGEPROCESS_LIB)
#  define MLCOLORIMETERIMAGEPROCESS_EXPORT Q_DECL_EXPORT
# else
#  define MLCOLORIMETERIMAGEPROCESS_EXPORT Q_DECL_IMPORT
# endif
#else
# define MLCOLORIMETERIMAGEPROCESS_EXPORT
#endif
