#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(MLTHROUGHFOCUSPROCESS_LIB)
#  define MLTHROUGHFOCUSPROCESS_EXPORT Q_DECL_EXPORT
# else
#  define MLTHROUGHFOCUSPROCESS_EXPORT Q_DECL_IMPORT
# endif
#else
# define MLTHROUGHFOCUSPROCESS_EXPORT
#endif
